//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.109.209.100:9081/uac/services/LoginSMS", ConfigurationName="ServiceReference3.CQWebServices")]
    public interface CQWebServices {
        
        // CODEGEN: 消息 LoginSMSRequest 的包装命名空间(http://chongqing.local.a4.asiainfo.com)以后生成的消息协定与默认值(http://10.109.209.100:9081/uac/services/LoginSMS)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WindowsFormsApplication2.ServiceReference3.LoginSMSResponse LoginSMS(WindowsFormsApplication2.ServiceReference3.LoginSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginLoginSMS(WindowsFormsApplication2.ServiceReference3.LoginSMSRequest request, System.AsyncCallback callback, object asyncState);
        
        WindowsFormsApplication2.ServiceReference3.LoginSMSResponse EndLoginSMS(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginSMS", WrapperNamespace="http://chongqing.local.a4.asiainfo.com", IsWrapped=true)]
    public partial class LoginSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestInfo;
        
        public LoginSMSRequest() {
        }
        
        public LoginSMSRequest(string RequestInfo) {
            this.RequestInfo = RequestInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginSMSResponse", WrapperNamespace="http://10.109.209.100:9081/uac/services/LoginSMS", IsWrapped=true)]
    public partial class LoginSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LoginSMSReturn;
        
        public LoginSMSResponse() {
        }
        
        public LoginSMSResponse(string LoginSMSReturn) {
            this.LoginSMSReturn = LoginSMSReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CQWebServicesChannel : WindowsFormsApplication2.ServiceReference3.CQWebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CQWebServicesClient : System.ServiceModel.ClientBase<WindowsFormsApplication2.ServiceReference3.CQWebServices>, WindowsFormsApplication2.ServiceReference3.CQWebServices {
        
        private BeginOperationDelegate onBeginLoginSMSDelegate;
        
        private EndOperationDelegate onEndLoginSMSDelegate;
        
        private System.Threading.SendOrPostCallback onLoginSMSCompletedDelegate;
        
        public CQWebServicesClient() {
        }
        
        public CQWebServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CQWebServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CQWebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CQWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<LoginSMSCompletedEventArgs> LoginSMSCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication2.ServiceReference3.LoginSMSResponse WindowsFormsApplication2.ServiceReference3.CQWebServices.LoginSMS(WindowsFormsApplication2.ServiceReference3.LoginSMSRequest request) {
            return base.Channel.LoginSMS(request);
        }
        
        public string LoginSMS(string RequestInfo) {
            WindowsFormsApplication2.ServiceReference3.LoginSMSRequest inValue = new WindowsFormsApplication2.ServiceReference3.LoginSMSRequest();
            inValue.RequestInfo = RequestInfo;
            WindowsFormsApplication2.ServiceReference3.LoginSMSResponse retVal = ((WindowsFormsApplication2.ServiceReference3.CQWebServices)(this)).LoginSMS(inValue);
            return retVal.LoginSMSReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsFormsApplication2.ServiceReference3.CQWebServices.BeginLoginSMS(WindowsFormsApplication2.ServiceReference3.LoginSMSRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginSMS(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLoginSMS(string RequestInfo, System.AsyncCallback callback, object asyncState) {
            WindowsFormsApplication2.ServiceReference3.LoginSMSRequest inValue = new WindowsFormsApplication2.ServiceReference3.LoginSMSRequest();
            inValue.RequestInfo = RequestInfo;
            return ((WindowsFormsApplication2.ServiceReference3.CQWebServices)(this)).BeginLoginSMS(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication2.ServiceReference3.LoginSMSResponse WindowsFormsApplication2.ServiceReference3.CQWebServices.EndLoginSMS(System.IAsyncResult result) {
            return base.Channel.EndLoginSMS(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndLoginSMS(System.IAsyncResult result) {
            WindowsFormsApplication2.ServiceReference3.LoginSMSResponse retVal = ((WindowsFormsApplication2.ServiceReference3.CQWebServices)(this)).EndLoginSMS(result);
            return retVal.LoginSMSReturn;
        }
        
        private System.IAsyncResult OnBeginLoginSMS(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string RequestInfo = ((string)(inValues[0]));
            return this.BeginLoginSMS(RequestInfo, callback, asyncState);
        }
        
        private object[] OnEndLoginSMS(System.IAsyncResult result) {
            string retVal = this.EndLoginSMS(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginSMSCompleted(object state) {
            if ((this.LoginSMSCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginSMSCompleted(this, new LoginSMSCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginSMSAsync(string RequestInfo) {
            this.LoginSMSAsync(RequestInfo, null);
        }
        
        public void LoginSMSAsync(string RequestInfo, object userState) {
            if ((this.onBeginLoginSMSDelegate == null)) {
                this.onBeginLoginSMSDelegate = new BeginOperationDelegate(this.OnBeginLoginSMS);
            }
            if ((this.onEndLoginSMSDelegate == null)) {
                this.onEndLoginSMSDelegate = new EndOperationDelegate(this.OnEndLoginSMS);
            }
            if ((this.onLoginSMSCompletedDelegate == null)) {
                this.onLoginSMSCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginSMSCompleted);
            }
            base.InvokeAsync(this.onBeginLoginSMSDelegate, new object[] {
                        RequestInfo}, this.onEndLoginSMSDelegate, this.onLoginSMSCompletedDelegate, userState);
        }
    }
}
